---
title: "A2-des"
author: "SKK"
date: "2024-04-05"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# packages
```{r}
install.packages("pacman")
pacman::p_load(tidyverse, tidymodels, gridExtra, ggplot)
install.packages("wordcloud")
library(wordcloud)
setwd('.')
```

# data
```{r}
# Specify the folder path
folder_path <- "nelson_data"

# List all CSV files in the folder
files <- list.files(folder_path, pattern = "\\.csv$", full.names = TRUE)

# Initialize an empty list to store the data frames
dfs <- list()

# Load each CSV file into a data frame and store it in the list
for (file in files) {
  df <- read.csv(file)
  dfs[[length(dfs) + 1]] <- df
}

# Combine all data frames into a single data frame
combined_df <- do.call(rbind, dfs)

# Print the combined data frame
print(combined_df)

```
## filter escape trials
```{r}
filter <- subset(combined_df, combined_df["answer"] != "escape")
```

# words frequency
```{r}
#check out equisse
```


# sentiment
```{r}
pacman::p_load(tidytext,textdata)
#add sentiment
sent <- filter %>% 
  rename(sentiment=comment) 
sent$sentiment <- as.character(sent$sentiment)
library(tidyr)

senti <- sent %>%
  unnest_tokens(word, answer) %>% 
  inner_join(get_sentiments("nrc"), by = c(word = "word"))

sent_with_tokens <- sent %>%
  unnest_tokens(word, answer) %>%
  left_join(get_sentiments("nrc"), by = c(word = "word")) %>%
  group_by(id,task) %>% 
  distinct(word, .keep_all = TRUE) %>% 
  mutate(sentiment.x="yeahe")
sentim <- sent_with_tokens[complete.cases(sent_with_tokens), ]

jane_austen_sentiment <- sent %>%
  inner_join(get_sentiments("nrc")) %>%
  mutate(sentiment = positive - negative)
# Iterate over each row in the dataframe
for (i in 1:nrow(sent)) {
  # Extract the text from the 'text' column
  msg <- sent$answer[i]
  
  # Calculate the sentiment using sentida()
  tryCatch({
  sentiment <- get_sentiments(msg, output = "total")
  # Assign the sentiment value to the corresponding row in the 'sentiment' column
  sent$sentiment[i] <- sentiment
  },
  error = function(e){
    sent$sentiment[i] <- NA
  }
  )
}

```

# plot
```{r}
sent$task <- as.factor(sent$task)
sent$group <- as.factor(sent$group)

set.seed(1234)
library(wordcloud)
install.packages("tm")
install.packages("slam")
library(tm)
library(slam)

sent$group <- as.character(sent$group)
mt <- filter(sent, task=="WordsOfMt Nelson Oval" )
hob <- filter(sent, task=="WordsOfengaging outdoor area")
# Define color palette
colors <- colorRampPalette(c("red", "orange", "yellow"))(100)

# Map sentiment scores to colors
color_map_mt <- cut(mt$sentiment, breaks = 100, labels = colors)
wordcloud::wordcloud(mt$answer,min.freq=1, )
wordcloud::wordcloud(hob$answer, min.freq=1, random.order=FALSE)
```

